Add stub for deprecated susfs_add_try_umount function
Fix compilation error:
- Add st_susfs_try_umount struct to include/linux/susfs.h
- Add susfs_add_try_umount stub function to fs/susfs.c
- Function is deprecated but still called from supercall.c